### ISSUE TITLE
hi! missing .exe file?

### ISSUE THREAD

**Issue by DutchMenace666** [creaktive/ACFTools#1]
Hello, 

I am trying to extract some data from an acf but i am missing the acftools.exe file. and when i use acftools.pl instead, perl only runs "acftools.pl" returning the how to use, but not the                              rest: (resp.   --extract=acf700 --acffile="f117a.acf") 

hope you can help me. 

Regards,

Bob [DM666]

**Comment by creaktive** [comment]
Hi! Unfortunately I do not have Windows anymore so I can not test :(
However, Windows has the ability to run a virtualized Linux environment nowadays. I would suggest to try to run it in a virtual Linux, be it the one that comes with Windows, or via Docker

**Comment by DutchMenace666** [comment]
Wow that's swift! 

Linux! Of course.. I'll get into it. Thank you, kind Sir. 

Have a nice day!
